### ISSUE TITLE
Icon property names are inconvenient

### ISSUE THREAD

**Issue by drobiazko** [elasticio/recipes#6]
Recipe properties `icon` and `image` have same meaning. It's hard to guess which one is large and which is small.

https://github.com/elasticio/recipes/blob/master/index.js#L84-L85

**Comment by asci** [comment]
https://github.com/elasticio/recipes/pull/5/files#diff-168726dbe96b3ce427e7fedce31bb0bcL84 looks like it will be fixed with this PR

**Comment by drobiazko** [comment]
So, it's gonna be used like this?

``` html
<img src="{{this.icon.large}}" class="sync-icon"/>
```

or 

``` html
<img src="{{this.icon.small}}" class="sync-icon"/>
```

**Comment by asci** [comment]
yea, but using word `images`:
`<img src="{{this.images.small}}" class="sync-icon"/>`

**Comment by drobiazko** [comment]
Okey, got it. Gonna close it once merged.
